AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Order Service
    Sample SAM Template for Order Service

Globals:
    Function:
        Timeout: 3
Resources:

    InvokingApi:
        Type: AWS::Serverless::HttpApi
        Properties:
          StageName: default
          CorsConfiguration:
            AllowOrigins: "'*'"
            AllowMethods: "'*'"
            AllowHeaders: "'*'"

    CreateOrderFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: CreateOrder.lambda_handler
            Runtime: python3.7
            Events:
                CreateOrder:
                    Type: HttpApi
                    Properties:
                        Path: /order
                        Method: post
                        ApiId: !Ref InvokingApi

    
    ProcessOrderFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: ProcessOrder.lambda_handler
            Runtime: python3.7
            Events:
                ProcessOrder:
                    Type: SQS
                    Properties:
                        Queue: !ImportValue OrderQueueUrl
                        BatchSize: 1
                OrderNotification:
                    Type: SNS
                    Properties:
                        Topic: !ImportValue OrderTopicArn
                    


    OrderQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: OrderQueue

    OrderNotficationTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: OrderNotificationTopic
            DisplayName: Order Notification Topic
        
    OrderNotificationSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: qtanweer.mts41ceme@gmail.com
            Protocol: email
            TopicArn: !Ref OrderNotficationTopic

Outputs:
    OrderQueueUrl:
        Description: "Order Queue URL"
        Value: !GetAtt OrderQueue.Arn
        Export:
            Name: OrderQueueUrl

    OrderTopicArn:
        Description: "Order Notification Topic"
        Value: !Ref OrderNotficationTopic
        Export:
            Name: OrderTopicArn






    

